from __future__ import annotations

from typing import Protocol

from ..domain.models import ExtractionResult, ValidationResult


class ValidationEngine(Protocol):
    def validate(self, document_result: ExtractionResult) -> ValidationResult: ...


class InvoiceTotalValidator(Protocol): ...
class QuantityValidator(Protocol): ...
class TaxBucketValidator(Protocol): ...
class RoundOffValidator(Protocol): ...
class BankBalanceValidator(Protocol): ...
class DuplicateValidator(Protocol): ...
class LedgerValidator(Protocol): ...
