"use client";

import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {apiContext,tenantHeaders} from "../lib/api";

type DocumentRow={document_id:string;original_filename:string;status:string;document_type:string;supplier:string;invoice_number:string};
type Preview={document_id:string;document_type:string;template:string;validation_status:string;export_allowed:boolean;columns:string[];rows:Record<string,unknown>[];summary:{rows:number;quantity:string;taxable:string;total:string}};

export function AccountingExcelWorkspace({invoiceMode=false}:{invoiceMode?:boolean}){
  const context=apiContext();const[documents,setDocuments]=useState<DocumentRow[]>([]);const[selected,setSelected]=useState("");const[preview,setPreview]=useState<Preview|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!context)return;const response=await fetch(`${context.apiUrl}/api/v2/documents?limit=100`,{headers:tenantHeaders(context)});if(response.ok){const items=(await response.json()).items as DocumentRow[];setDocuments(invoiceMode?items.filter(item=>["Tax Invoice","Credit Note","Stock Transfer","Custom"].includes(item.document_type||"Custom")):items)}},[context,invoiceMode]);
  useEffect(()=>{void load()},[load]);
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!context)return;const input=event.currentTarget.elements.namedItem("file") as HTMLInputElement;const file=input.files?.[0];if(!file)return;setBusy(true);setMessage("");const form=new FormData();form.append("file",file);
    const response=await fetch(`${context.apiUrl}/api/v2/documents/upload`,{method:"POST",headers:tenantHeaders(context),body:form});const body=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(body?.detail?.message||body?.detail||"Upload failed.");return}setMessage(`Processed as ${body.status}.`);setSelected(body.document_id);input.value="";await load();if(body.document_id)await openPreview(body.document_id)}
  async function openPreview(documentId:string){if(!context||!documentId)return;setSelected(documentId);setBusy(true);setMessage("");const response=await fetch(`${context.apiUrl}/api/v2/documents/${documentId}/excel-preview`,{headers:tenantHeaders(context)});setBusy(false);if(response.ok)setPreview(await response.json());else{setPreview(null);const body=await response.json().catch(()=>({}));setMessage(typeof body.detail==="string"?body.detail:"Preview is not available.")}}
  async function download(){if(!context||!preview)return;setBusy(true);const response=await fetch(`${context.apiUrl}/api/v2/documents/${preview.document_id}/excel`,{method:"POST",headers:tenantHeaders(context)});setBusy(false);if(!response.ok){const body=await response.json().catch(()=>({}));setMessage(typeof body.detail==="string"?body.detail:"Excel export is blocked.");return}const blob=await response.blob();const disposition=response.headers.get("Content-Disposition")||"";const name=/filename="([^"]+)"/.exec(disposition)?.[1]||"accounting_export.xlsx";const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);setMessage("Verified Excel export downloaded and added to export history.")}
  if(!context)return <div className="config-state">Sign in and choose an authorized company.</div>;
  return <><form className="upload-panel" onSubmit={upload}><label><strong>{invoiceMode?"Upload invoice-like PDF":"Upload PDF for Excel"}</strong><span>Known formats use the certified deterministic parser. Validation failures remain visible and block export.</span><input name="file" type="file" accept="application/pdf,.pdf" required/></label><button className="primary" disabled={busy}>{busy?"Workingâ€¦":"Upload and process"}</button></form>
    {message&&<p className="inline-message" role="status">{message}</p>}<section className="panel"><div className="panel-heading"><div><p className="eyebrow">Company documents</p><h2>{invoiceMode?"Invoice Converter":"PDF to Excel"}</h2></div><label className="document-picker"><span>Document</span><select value={selected} onChange={event=>void openPreview(event.target.value)}><option value="">Choose a processed document</option>{documents.map(document=><option value={document.document_id} key={document.document_id}>{document.original_filename} Â· {document.document_type||"Custom"} Â· {document.status}</option>)}</select></label></div>
      {preview&&<><div className="export-summary"><article><span>Format</span><strong>{preview.document_type||"Custom"}</strong></article><article><span>Rows</span><strong>{preview.summary.rows}</strong></article><article><span>Quantity</span><strong>{preview.summary.quantity}</strong></article><article><span>Taxable</span><strong>₹{preview.summary.taxable}</strong></article><article><span>Total</span><strong>₹{preview.summary.total}</strong></article><article><span>Validation</span><strong className={`status status-${preview.validation_status.toLowerCase()}`}>{preview.validation_status}</strong></article></div>
        <div className="table-wrap"><table><thead><tr>{preview.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{preview.rows.map((row,index)=><tr key={index}>{preview.columns.map(column=><td key={column}>{String(row[column]??"")}</td>)}</tr>)}</tbody></table>{!preview.rows.length&&<div className="empty-table">No accounting rows are available. Open Template Studio or Review Queue.</div>}</div>
        <div className="export-actions"><Link className="filter-button" href={`/documents/${preview.document_id}`}>Open evidence</Link><Link className="filter-button" href={`/template-studio?documentId=${preview.document_id}`}>Review template</Link><button className="primary" disabled={!preview.export_allowed||busy} onClick={()=>void download()}>{preview.export_allowed?"Download verified Excel":"Export blocked by validation"}</button></div></>}
    </section></>;
}
