"use client";

import { useEffect, useState } from "react";
import { apiContext, tenantHeaders } from "../lib/api";

type Status = {phase:string;mode:string;billing_mode:string;privacy_mode:string;local:{configured:boolean;runtime_healthy:boolean;model:string|null};cloud:{configured:boolean;deployed_runtime_verified:boolean;model:string|null;raw_payload_logging:boolean};quota:{used:number;reserved:number;limit:number;remaining:number;state:string;reset_at:string}};
type Hardware={logical_cpu_count:number;available_ram_gb:number|null;gpu_name:string;free_disk_gb:number;profile:string;runtime_healthy:boolean};

export function AiDashboard(){const context=apiContext();const [status,setStatus]=useState<Status|null>(null);const [hardware,setHardware]=useState<Hardware|null>(null);const [error,setError]=useState("");useEffect(()=>{if(!context)return;Promise.all([fetch(`${context.apiUrl}/api/v2/ai/status`,{headers:tenantHeaders(context)}),fetch(`${context.apiUrl}/api/v2/ai/setup/hardware`,{headers:tenantHeaders(context)})]).then(async([a,b])=>{if(!a.ok||!b.ok)throw new Error("AI status unavailable");setStatus(await a.json());setHardware(await b.json())}).catch(value=>setError(value.message))},[context]);if(!context)return <div className="config-state">Set tenant IDs to inspect AI setup.</div>;if(error)return <div className="config-state">{error}</div>;if(!status||!hardware)return <div className="config-state">Loading local and cloud runtime status…</div>;const used=(status.quota.used+status.quota.reserved)/status.quota.limit*100;return <div className="ai-dashboard-grid"><section className="panel"><p className="eyebrow">Certification state</p><h2>{status.phase.replaceAll("_"," ")}</h2><p className="muted">Architecture and deterministic safety are available. Runtime labels stay unverified until real inference succeeds.</p><dl className="ai-kv"><div><dt>Operating mode</dt><dd>{status.mode}</dd></div><div><dt>Billing</dt><dd>{status.billing_mode}</dd></div><div><dt>Privacy</dt><dd>{status.privacy_mode}</dd></div><div><dt>Authority</dt><dd>Deterministic + human</dd></div></dl></section>
    <section className="panel"><p className="eyebrow">Local runtime</p><h2>{status.local.runtime_healthy?"Healthy":"Not installed / running"}</h2><dl className="ai-kv"><div><dt>Profile</dt><dd>{hardware.profile}</dd></div><div><dt>CPU</dt><dd>{hardware.logical_cpu_count} logical</dd></div><div><dt>RAM</dt><dd>{hardware.available_ram_gb??"Unknown"} GB</dd></div><div><dt>GPU</dt><dd>{hardware.gpu_name}</dd></div><div><dt>Disk free</dt><dd>{hardware.free_disk_gb} GB</dd></div></dl><p className="muted">No model is downloaded automatically. Recommended start: 1B–3B instruct GGUF, Q4, CPU-oriented.</p></section>
    <section className="panel"><p className="eyebrow">Cloudflare boundary</p><h2>{status.cloud.deployed_runtime_verified?"Runtime certified":status.cloud.configured?"Configured, verification required":"Not configured"}</h2><dl className="ai-kv"><div><dt>Deployment</dt><dd>{status.cloud.deployed_runtime_verified?"Verified":"Not verified"}</dd></div><div><dt>Payload logs</dt><dd>{status.cloud.raw_payload_logging?"On":"Off"}</dd></div><div><dt>Secrets</dt><dd>Server-side only</dd></div></dl><p className="muted">Browser → FastAPI → signed development Worker → Workers AI. Runtime certification must be enabled explicitly after live verification.</p></section>
    <section className="panel"><p className="eyebrow">Conservative application quota ledger</p><h2>{status.quota.remaining.toLocaleString()} estimated neurons remaining</h2><p>Provider-reported neuron usage is unavailable; this is a fail-safe application estimate, not an authoritative Cloudflare balance.</p><progress value={used} max={100}/><div className="quota-thresholds"><span>85% warning</span><span>93% critical</span><span>95% hard stop</span></div><dl className="ai-kv"><div><dt>Accounted estimate</dt><dd>{status.quota.used}</dd></div><div><dt>Reserved estimate</dt><dd>{status.quota.reserved}</dd></div><div><dt>Reset</dt><dd>{new Date(status.quota.reset_at).toLocaleString()}</dd></div></dl></section></div>}
