"use client";

import { useState } from "react";
import { apiContext, tenantHeaders } from "../lib/api";

type ProposalAction = { action: string; payload: Record<string, unknown>; rationale: string; source_references: string[]; confidence: "HIGH"|"MEDIUM"|"LOW"; validation_impact: string; risk: string };
type Result = { state: string; reason?: string; proposal?: { summary: string; actions: ProposalAction[]; provider: string; model: string }; payload_preview?: { redaction_counts: Record<string, number> } };

export function AiDocumentAssistant({versionId, revision, selected, onApplied}:{versionId:string;revision:number;selected:Record<string,unknown>|null;onApplied:()=>Promise<void>}) {
  const context=apiContext(); const [request,setRequest]=useState(""); const [result,setResult]=useState<Result|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function propose(){if(!context||!request.trim())return;setBusy(true);setMessage("");try{const response=await fetch(`${context.apiUrl}/api/v2/ai/proposals`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({intent:"improve_mapping",text:request,selection:selected||{},mode:"HYBRID_PRIVATE",privacy_mode:"BALANCED",requires_vision:false})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Assistant request failed");setResult(body);if(body.state!=="READY_FOR_REVIEW")setMessage(body.reason||"No authorized AI runtime is available.")}catch(error){setMessage(error instanceof Error?error.message:"Assistant failed")}finally{setBusy(false)}}
  async function apply(item:ProposalAction){if(!context)return;setBusy(true);setMessage("");try{const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}/actions`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({revision,action:item.action,payload:item.payload})});const body=await response.json();if(!response.ok)throw new Error(body.detail?.message||body.detail||"Action failed deterministic validation");await onApplied();setMessage("Action applied to the draft. Run deterministic preview/tests before approval.")}catch(error){setMessage(error instanceof Error?error.message:"Action failed")}finally{setBusy(false)}}
  return <div className="ai-assistant"><div className="assistant-heading"><div><span>AI</span><div><strong>Restricted Document Assistant</strong><small>Proposals only · human review required</small></div></div><span className="status status-review">HYBRID PRIVATE</span></div>
    <div className="assistant-compose"><textarea value={request} onChange={event=>setRequest(event.target.value)} maxLength={4000} placeholder="Ask for a template mapping improvement. Text is untrusted and masked before cloud eligibility."/><button disabled={busy||!request.trim()} onClick={propose}>{busy?"Checking…":"Propose actions"}</button></div>
    {message&&<p className="assistant-message">{message}</p>}{result?.payload_preview&&<p className="assistant-privacy">Cloud preview: {Object.entries(result.payload_preview.redaction_counts).map(([key,value])=>`${key} ${value}`).join(" · ")||"no identifiers detected"} · reversible map transmitted: no</p>}
    {result?.proposal&&<div className="proposal-list"><div><strong>{result.proposal.summary}</strong><small>{result.proposal.provider} · {result.proposal.model}</small></div>{result.proposal.actions.map((item,index)=><article key={`${item.action}-${index}`}><header><strong>{item.action.replaceAll("_"," ")}</strong><span className={`confidence confidence-${item.confidence.toLowerCase()}`}>{item.confidence}</span></header><p>{item.rationale}</p><small>Source: {item.source_references.join(", ")||"model proposal"}</small><small>Validation impact: {item.validation_impact}</small><details><summary>Preview payload</summary><pre>{JSON.stringify(item.payload,null,2)}</pre></details><button disabled={busy} onClick={()=>apply(item)}>Apply this action to draft</button></article>)}</div>}
    <p className="assistant-boundary">Cannot approve templates, post vouchers, reconcile bank entries, change permissions, execute code, or browse arbitrary URLs.</p>
  </div>;
}
