"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {apiContext,tenantHeaders} from "../lib/api";

type DocumentRow={document_id:string;original_filename:string;status:string};
type BankRow={"Txn Date":string;"Description":string;"Type":string;"Withdrawal":string;"Deposit":string;"Balance":string;"Mapped Ledger":string;"Matched By":string;"Status":string};
type Preview={rows:BankRow[];reconciliation:{opening:string;credits:string;debits:string;calculated_closing:string;statement_closing:string;difference:string;status:string};bank_account:{bank_ledger:string;account_hint:string}|null;validation_status:string;export_allowed:boolean};

export function BankStatementWorkspace(){
  const context=apiContext();const[documents,setDocuments]=useState<DocumentRow[]>([]);const[selected,setSelected]=useState("");const[preview,setPreview]=useState<Preview|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const loadDocuments=useCallback(async()=>{if(!context)return;const response=await fetch(`${context.apiUrl}/api/v2/documents?limit=100`,{headers:tenantHeaders(context)});if(response.ok)setDocuments((await response.json()).items)},[context]);useEffect(()=>{void loadDocuments()},[loadDocuments]);
  async function open(documentId:string){if(!context||!documentId)return;setSelected(documentId);setBusy(true);const response=await fetch(`${context.apiUrl}/api/v2/bank/${documentId}/preview`,{headers:tenantHeaders(context)});setBusy(false);if(response.ok){setPreview(await response.json());setMessage("")}else{setPreview(null);setMessage("Bank preview is unavailable for this document.")}}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!context)return;const input=event.currentTarget.elements.namedItem("file") as HTMLInputElement;const file=input.files?.[0];if(!file)return;const form=new FormData();form.append("file",file);setBusy(true);const response=await fetch(`${context.apiUrl}/api/v2/documents/upload`,{method:"POST",headers:tenantHeaders(context),body:form});const body=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(body?.detail?.message||"Upload failed.");return}input.value="";await loadDocuments();await open(body.document_id)}
  async function map(row:BankRow,form:HTMLFormElement){if(!context)return;const data=new FormData(form);const response=await fetch(`${context.apiUrl}/api/v2/mappings`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({tool:"bank",platform:"",pattern:data.get("pattern"),voucher_type:row.Type,ledger:data.get("ledger"),match_type:data.get("match_type")})});if(response.ok){setMessage("Bank narration mapping saved and audited.");await open(selected)}else setMessage("Mapping could not be saved.")}
  async function download(){if(!context||!selected)return;setBusy(true);const response=await fetch(`${context.apiUrl}/api/v2/bank/${selected}/xml`,{method:"POST",headers:tenantHeaders(context)});setBusy(false);if(!response.ok){setMessage("XML is blocked until reconciliation, bank account, and every narration mapping are verified.");return}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="bank_statement.xml";anchor.click();URL.revokeObjectURL(url);setMessage("Reconciled Bank XML downloaded.")}
  if(!context)return <div className="config-state">Sign in and choose an authorized company.</div>;
  return <><form className="upload-panel" onSubmit={upload}><label><strong>Upload bank statement PDF</strong><span>Transactions, account detection, narration mappings, and closing balance are checked before XML.</span><input name="file" type="file" accept="application/pdf,.pdf" required/></label><button className="primary" disabled={busy}>{busy?"Workingâ€¦":"Upload and reconcile"}</button></form>{message&&<p className="inline-message" role="status">{message}</p>}
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Balance-safe voucher generation</p><h2>Bank Statement XML</h2></div><label className="document-picker"><span>Document</span><select value={selected} onChange={event=>void open(event.target.value)}><option value="">Choose document</option>{documents.map(document=><option value={document.document_id} key={document.document_id}>{document.original_filename} Â· {document.status}</option>)}</select></label></div>
      {preview&&<><div className={`reconciliation-banner reconciliation-${preview.reconciliation.status.toLowerCase()}`}><div><span>Opening Balance</span><strong>₹{preview.reconciliation.opening}</strong></div><div><span>Credits</span><strong>₹{preview.reconciliation.credits}</strong></div><div><span>Debits</span><strong>₹{preview.reconciliation.debits}</strong></div><div><span>Calculated Closing</span><strong>₹{preview.reconciliation.calculated_closing}</strong></div><div><span>Statement Closing</span><strong>₹{preview.reconciliation.statement_closing}</strong></div><div><span>Difference</span><strong>₹{preview.reconciliation.difference}</strong></div></div>
        <p className="inline-message">Bank ledger: {preview.bank_account?`${preview.bank_account.bank_ledger} (${preview.bank_account.account_hint})`:"Not configured"} Â· Validation: {preview.validation_status}</p>
        <div className="table-wrap"><table><thead><tr><th>Date / narration</th><th>Type</th><th>Credit</th><th>Debit</th><th>Balance</th><th>Ledger mapping</th><th>Status</th></tr></thead><tbody>{preview.rows.map((row,index)=><tr key={`${row["Txn Date"]}-${index}`}><td>{row["Txn Date"]}<small>{row.Description}</small></td><td>{row.Type}</td><td>{row.Deposit}</td><td>{row.Withdrawal}</td><td>{row.Balance}</td><td>{row.Status==="OK"?<><strong>{row["Mapped Ledger"]}</strong><small>{row["Matched By"]}</small></>:<form className="inline-map" onSubmit={event=>{event.preventDefault();void map(row,event.currentTarget)}}><input name="pattern" defaultValue={row.Description} required/><input name="ledger" placeholder="Ledger name" required/><select name="match_type"><option>contains</option><option>smart_contains</option><option>equals</option><option>starts_with</option><option>regex</option></select><button className="filter-button">Save</button></form>}</td><td><span className={`status status-${row.Status.toLowerCase()}`}>{row.Status}</span></td></tr>)}</tbody></table></div><div className="export-actions"><button className="primary" disabled={!preview.export_allowed||busy} onClick={()=>void download()}>{preview.export_allowed?"Download reconciled XML":"XML blocked"}</button></div></>}
    </section></>;
}
