"use client";

import {useEffect,useState} from "react";
import {apiContext,tenantHeaders} from "../lib/api";

type Category={source_rows:number;candidate_target_rows:number;exact:number;normalized:number;existing_exact:number;duplicates:number;conflicts:number;invalid:number;missing:number};
type Preview={preview_id:string;source_file:string;source_sha256:string;expected_sha256:string;hash_matches_expected:boolean;apply_allowed:boolean;categories:Record<string,Category>;company_counts:Record<string,Record<string,number>>;blocking_reasons:string[]};

export function DataMigrationWorkspace(){
  const context=apiContext();const[preview,setPreview]=useState<Preview|null>(null);const[history,setHistory]=useState<Array<Record<string,unknown>>>([]);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function loadHistory(){if(!context)return;const response=await fetch(`${context.apiUrl}/api/v2/phase6c/migration/previews`,{headers:tenantHeaders(context)});if(response.ok)setHistory((await response.json()).items||[])}
  useEffect(()=>{void loadHistory()},[]);
  async function runPreview(){if(!context)return;setBusy(true);setMessage("");const response=await fetch(`${context.apiUrl}/api/v2/phase6c/migration/preview`,{method:"POST",headers:tenantHeaders(context)});const body=await response.json().catch(()=>({}));if(response.ok){setPreview(body);setMessage("Preview complete. SQLite was opened read-only and no PostgreSQL masters were changed.");await loadHistory()}else setMessage(typeof body.detail==="string"?body.detail:"Migration preview failed.");setBusy(false)}
  async function apply(){if(!context||!preview||!preview.apply_allowed)return;if(!window.confirm("Import this exact preview into PostgreSQL? SQLite will remain unchanged."))return;setBusy(true);const response=await fetch(`${context.apiUrl}/api/v2/phase6c/migration/${preview.preview_id}/apply`,{method:"POST",headers:tenantHeaders(context)});const body=await response.json().catch(()=>({}));setMessage(response.ok?"Migration applied. Run a fresh preview to prove the second run creates no duplicates.":typeof body.detail==="string"?body.detail:"Migration was not applied.");if(response.ok)setPreview(null);await loadHistory();setBusy(false)}
  if(!context)return <div className="config-state">Sign in as an owner or administrator and select an authorized company.</div>;
  return <div className="phase6c-stack">{message&&<p className="inline-message" role="status">{message}</p>}<section className="panel migration-source"><div><p className="eyebrow">Settings / Data Migration</p><h2>Existing Business Automation Database</h2><p>The source is fixed to <code>data/business_rules.db</code>. Preview always runs first using SQLite immutable/read-only mode.</p></div><button className="primary" disabled={busy} onClick={()=>void runPreview()}>{busy?"Checking…":"Run validation preview"}</button></section>
    {preview&&<><section className={`status-banner ${preview.hash_matches_expected?"":"danger-banner"}`}><p><strong>Source SHA-256</strong><br/><code>{preview.source_sha256}</code></p><span className={`status ${preview.hash_matches_expected?"status-verified":"status-blocked"}`}>{preview.hash_matches_expected?"CERTIFIED SOURCE":"HASH MISMATCH"}</span></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Dry run only</p><h2>Migration Preview</h2></div><button className="primary" disabled={!preview.apply_allowed||busy} onClick={()=>void apply()}>{preview.apply_allowed?"Confirm migration":"Resolve blockers first"}</button></div><div className="table-wrap"><table><thead><tr><th>Category</th><th>Source</th><th>Candidate</th><th>Exact</th><th>Normalized</th><th>Already exact</th><th>Duplicates</th><th>Conflicts</th><th>Invalid</th></tr></thead><tbody>{Object.entries(preview.categories).map(([name,item])=><tr key={name}><td><strong>{name.replaceAll("_"," ")}</strong></td><td>{item.source_rows}</td><td>{item.candidate_target_rows}</td><td>{item.exact}</td><td>{item.normalized}</td><td>{item.existing_exact}</td><td>{item.duplicates}</td><td>{item.conflicts}</td><td>{item.invalid}</td></tr>)}</tbody></table></div></section><section className="panel"><p className="eyebrow">Company ownership</p><h2>Company-by-company source counts</h2><div className="company-count-grid">{Object.entries(preview.company_counts).map(([company,counts])=><article key={company}><h3>{company}</h3>{Object.entries(counts).map(([name,value])=><p key={name}><span>{name.replaceAll("_"," ")}</span><strong>{value}</strong></p>)}</article>)}</div></section></>}
    <section className="panel"><p className="eyebrow">Audit trail</p><h2>Recent previews</h2>{history.length===0?<p className="muted">No migration preview has been created for this organization.</p>:<div className="table-wrap"><table><thead><tr><th>Created</th><th>Hash</th><th>Status</th></tr></thead><tbody>{history.map(item=><tr key={String(item.id)}><td>{new Date(String(item.created_at)).toLocaleString()}</td><td><code>{String(item.source_sha256).slice(0,16)}…</code></td><td><span className={`status ${item.status==="APPLIED"?"status-verified":"status-info"}`}>{String(item.status)}</span></td></tr>)}</tbody></table></div>}</section></div>;
}
