"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {apiContext,tenantHeaders} from "../lib/api";

type DocumentRow={document_id:string;original_filename:string;status:string};
type MarketRow={"Description":string;"Platform":string;"PDF Doc Type":string;"Tally Voucher Type":string;"Mapped Ledger":string;"Matched By":string;"Taxable":string;"CGST":string;"SGST":string;"IGST":string;"Total":string;"Status":string;"Issue":string};
type Preview={rows:MarketRow[];totals:Record<string,string>;validation_status:string;export_allowed:boolean};

export function MarketplaceWorkspace(){
  const context=apiContext();const[documents,setDocuments]=useState<DocumentRow[]>([]);const[selected,setSelected]=useState("");const[preview,setPreview]=useState<Preview|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const loadDocuments=useCallback(async()=>{if(!context)return;const response=await fetch(`${context.apiUrl}/api/v2/documents?limit=100`,{headers:tenantHeaders(context)});if(response.ok)setDocuments((await response.json()).items)},[context]);useEffect(()=>{void loadDocuments()},[loadDocuments]);
  async function open(documentId:string){if(!context||!documentId)return;setSelected(documentId);setBusy(true);const response=await fetch(`${context.apiUrl}/api/v2/marketplace/${documentId}/preview`,{headers:tenantHeaders(context)});setBusy(false);if(response.ok){setPreview(await response.json());setMessage("")}else{setPreview(null);setMessage("Marketplace preview is unavailable for this document.")}}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!context)return;const input=event.currentTarget.elements.namedItem("file") as HTMLInputElement;const file=input.files?.[0];if(!file)return;const form=new FormData();form.append("file",file);setBusy(true);const response=await fetch(`${context.apiUrl}/api/v2/documents/upload`,{method:"POST",headers:tenantHeaders(context),body:form});const body=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(body?.detail?.message||"Upload failed.");return}input.value="";await loadDocuments();await open(body.document_id)}
  async function map(row:MarketRow,form:HTMLFormElement){if(!context)return;const data=new FormData(form);const response=await fetch(`${context.apiUrl}/api/v2/mappings`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({tool:"marketplace",platform:row.Platform,pattern:row.Description,voucher_type:row["PDF Doc Type"],ledger:data.get("ledger"),match_type:data.get("match_type")})});if(response.ok){setMessage("Mapping saved with audit evidence.");await open(selected)}else setMessage("Mapping could not be saved.")}
  async function download(){if(!context||!selected)return;setBusy(true);const response=await fetch(`${context.apiUrl}/api/v2/marketplace/${selected}/xml`,{method:"POST",headers:tenantHeaders(context)});setBusy(false);if(!response.ok){setMessage("XML export remains blocked. Resolve every review row and required master first.");return}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="marketplace.xml";anchor.click();URL.revokeObjectURL(url);setMessage("Verified Marketplace XML downloaded.")}
  if(!context)return <div className="config-state">Sign in and choose an authorized company.</div>;
  return <><form className="upload-panel" onSubmit={upload}><label><strong>Upload marketplace PDF</strong><span>Supplier, document type, mappings, GST, and voucher rules are validated before XML export.</span><input name="file" type="file" accept="application/pdf,.pdf" required/></label><button className="primary" disabled={busy}>{busy?"Workingâ€¦":"Upload and parse"}</button></form>{message&&<p className="inline-message" role="status">{message}</p>}
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Purchase and Debit Note classification</p><h2>Marketplace XML</h2></div><label className="document-picker"><span>Document</span><select value={selected} onChange={event=>void open(event.target.value)}><option value="">Choose document</option>{documents.map(document=><option value={document.document_id} key={document.document_id}>{document.original_filename} Â· {document.status}</option>)}</select></label></div>
      {preview&&<><div className="export-summary">{["Taxable","CGST","SGST","IGST","Total"].map(key=><article key={key}><span>{key}</span><strong>₹{preview.totals[key]}</strong></article>)}<article><span>Validation</span><strong className={`status status-${preview.validation_status.toLowerCase()}`}>{preview.validation_status}</strong></article></div>
        <div className="table-wrap"><table><thead><tr><th>Description / platform</th><th>Voucher</th><th>Taxable / GST</th><th>Mapping</th><th>Status</th></tr></thead><tbody>{preview.rows.map((row,index)=><tr key={`${row.Description}-${index}`}><td><strong>{row.Description}</strong><small>{row.Platform} Â· {row["PDF Doc Type"]}</small></td><td>{row["Tally Voucher Type"]}</td><td>₹{row.Taxable}<small>CGST {row.CGST} Â· SGST {row.SGST} Â· IGST {row.IGST}</small></td><td>{row.Status==="OK"?<><strong>{row["Mapped Ledger"]}</strong><small>{row["Matched By"]}</small></>:<form className="inline-map" onSubmit={event=>{event.preventDefault();void map(row,event.currentTarget)}}><input name="ledger" placeholder="Ledger name" required/><select name="match_type"><option>contains</option><option>smart_contains</option><option>equals</option><option>starts_with</option><option>regex</option></select><button className="filter-button">Save mapping</button></form>}</td><td><span className={`status status-${row.Status.toLowerCase()}`}>{row.Status}</span><small>{row.Issue||"Ready"}</small></td></tr>)}</tbody></table></div><div className="export-actions"><button className="primary" disabled={!preview.export_allowed||busy} onClick={()=>void download()}>{preview.export_allowed?"Download verified XML":"Resolve review rows before export"}</button></div></>}
    </section></>;
}
