"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {apiContext,tenantHeaders} from "../lib/api";

type Snapshot={companies:Array<Record<string,unknown>>;bank_accounts:Array<Record<string,unknown>>;party_ledgers:Array<Record<string,unknown>>;gst_ledgers:Array<Record<string,unknown>>;ledger_mappings:Array<Record<string,unknown>>;voucher_rules:Array<Record<string,unknown>>};
const empty:Snapshot={companies:[],bank_accounts:[],party_ledgers:[],gst_ledgers:[],ledger_mappings:[],voucher_rules:[]};

export function MastersWorkspace(){
  const context=apiContext();const[data,setData]=useState<Snapshot>(empty);const[message,setMessage]=useState("");const[importPreview,setImportPreview]=useState<{preview_id:string;summary:Record<string,number>;rows:Array<Record<string,unknown>>;apply_allowed:boolean}|null>(null);
  const load=useCallback(async()=>{if(!context)return;const response=await fetch(`${context.apiUrl}/api/v2/masters`,{headers:tenantHeaders(context)});if(response.ok)setData(await response.json());else setMessage("Masters could not be loaded.")},[context]);useEffect(()=>{void load()},[load]);
  async function save(event:FormEvent<HTMLFormElement>,path:string,fields:string[]){event.preventDefault();if(!context)return;const form=new FormData(event.currentTarget);const payload=Object.fromEntries(fields.map(field=>[field,form.get(field)]));const response=await fetch(`${context.apiUrl}/api/v2/masters/${path}`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify(payload)});if(response.ok){event.currentTarget.reset();setMessage("Master saved with audit evidence.");await load()}else{const body=await response.json().catch(()=>({}));setMessage(typeof body.detail==="string"?body.detail:"Master could not be saved.")}}
  async function exportMappings(){if(!context)return;const response=await fetch(`${context.apiUrl}/api/v2/masters/mappings/export`,{headers:tenantHeaders(context)});if(!response.ok){setMessage("Mapping workbook could not be exported.");return}const url=URL.createObjectURL(await response.blob());const anchor=document.createElement("a");anchor.href=url;anchor.download="ledger_mappings.xlsx";anchor.click();URL.revokeObjectURL(url)}
  async function previewImport(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!context)return;const input=event.currentTarget.elements.namedItem("workbook") as HTMLInputElement;const file=input.files?.[0];if(!file)return;const form=new FormData();form.append("file",file);const response=await fetch(`${context.apiUrl}/api/v2/masters/mappings/import-preview`,{method:"POST",headers:tenantHeaders(context),body:form});const body=await response.json().catch(()=>({}));if(response.ok){setImportPreview(body);setMessage("Preview created. No mapping has been changed.")}else setMessage(typeof body.detail==="string"?body.detail:"Workbook preview failed.")}
  async function applyImport(){if(!context||!importPreview)return;const response=await fetch(`${context.apiUrl}/api/v2/masters/mappings/import/${importPreview.preview_id}/apply`,{method:"POST",headers:tenantHeaders(context)});if(response.ok){setMessage("Mapping import applied after PostgreSQL snapshot backup.");setImportPreview(null);await load()}else setMessage("Mapping import was not applied.")}
  if(!context)return <div className="config-state">Sign in and choose an authorized company.</div>;
  return <>{message&&<p className="inline-message" role="status">{message}</p>}<div className="masters-grid">
    <section className="panel"><p className="eyebrow">Masked account identification</p><h2>Bank Accounts</h2><form className="master-form" onSubmit={event=>void save(event,"bank-accounts",["account_hint","bank_ledger"])}><input name="account_hint" placeholder="Last 4â€“8 characters" minLength={4} maxLength={8} required/><input name="bank_ledger" placeholder="Tally bank ledger" required/><button className="primary">Save</button></form>{data.bank_accounts.map((item,index)=><p className="master-row" key={index}><strong>{String(item.bank_ledger)}</strong><span>{String(item.account_hint)}</span></p>)}</section>
    <section className="panel"><p className="eyebrow">Marketplace masters</p><h2>Party Ledgers</h2><form className="master-form" onSubmit={event=>void save(event,"party-ledgers",["platform","party_ledger","party_gstin","state"])}><input name="platform" placeholder="amazon / flipkart / meesho" required/><input name="party_ledger" placeholder="Party ledger" required/><input name="party_gstin" placeholder="GSTIN (optional)"/><input name="state" placeholder="State (optional)"/><button className="primary">Save</button></form>{data.party_ledgers.map((item,index)=><p className="master-row" key={index}><strong>{String(item.platform)}</strong><span>{String(item.party_ledger)}</span></p>)}</section>
    <section className="panel"><p className="eyebrow">Independent tax buckets</p><h2>GST Ledgers</h2><form className="master-form" onSubmit={event=>void save(event,"gst-ledgers",["tax_type","ledger_name"])}><select name="tax_type"><option>CGST</option><option>SGST</option><option>IGST</option></select><input name="ledger_name" placeholder="Input GST ledger" required/><button className="primary">Save</button></form>{data.gst_ledgers.map((item,index)=><p className="master-row" key={index}><strong>{String(item.tax_type)}</strong><span>{String(item.ledger_name)}</span></p>)}</section>
    <section className="panel"><p className="eyebrow">Accounting classification</p><h2>Voucher Rules</h2><form className="master-form" onSubmit={event=>void save(event,"voucher-rules",["platform","document_type","tally_voucher_type","sign_mode"])}><input name="platform" placeholder="Platform" required/><select name="document_type"><option>Tax Invoice</option><option>Credit Note</option></select><select name="tally_voucher_type"><option>Purchase</option><option>Debit Note</option></select><select name="sign_mode"><option value="charge">Charge</option><option value="reverse">Reverse</option></select><button className="primary">Save</button></form>{data.voucher_rules.map((item,index)=><p className="master-row" key={index}><strong>{String(item.platform)} Â· {String(item.document_type)}</strong><span>{String(item.tally_voucher_type)} Â· {String(item.sign_mode)}</span></p>)}</section>
  </div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Current PostgreSQL data</p><h2>Ledger Mappings</h2></div><div className="export-actions"><span>{data.ledger_mappings.length} mappings</span><button className="filter-button" onClick={()=>void exportMappings()}>Export workbook</button></div></div><form className="mapping-import" onSubmit={previewImport}><label><span>Edited mapping workbook</span><input name="workbook" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required/></label><button className="filter-button">Preview import</button></form>
    {importPreview&&<div className="import-preview"><div className="export-summary">{Object.entries(importPreview.summary).map(([key,value])=><article key={key}><span>{key}</span><strong>{value}</strong></article>)}</div><p>No data changes occur until Apply is selected. A PostgreSQL mapping snapshot is created first.</p><button className="primary" disabled={!importPreview.apply_allowed} onClick={()=>void applyImport()}>{importPreview.apply_allowed?"Apply validated changes":"Resolve invalid/conflicting rows"}</button></div>}
    <div className="table-wrap"><table><thead><tr><th>Tool</th><th>Platform</th><th>Pattern</th><th>Match</th><th>Ledger</th><th>Status</th></tr></thead><tbody>{data.ledger_mappings.map((item,index)=><tr key={index}><td>{String(item.tool)}</td><td>{String(item.platform||"all")}</td><td>{String(item.pattern)}</td><td>{String(item.match_type)}</td><td>{String(item.ledger)}</td><td>{item.enabled?"ACTIVE":"DISABLED"}</td></tr>)}</tbody></table></div></section></>;
}
