"use client";

import {useEffect,useState} from "react";
import {apiContext,tenantHeaders} from "../lib/api";

type DocumentItem={id:string;original_filename?:string;filename?:string;status:string};
type Field={field:string;legacy:unknown;v2:unknown;status:string};
type Result={run_id:string;mode:string;reference?:Record<string,unknown>;v2?:Record<string,unknown>;comparison?:{status:string;matches:number;differences:number;unexplained_differences:number;reason?:string;fields:Field[]}};

function value(value:unknown){if(value===null||value===undefined||value==="")return "—";return typeof value==="object"?JSON.stringify(value):String(value)}

export function ParityWorkspace(){
  const context=apiContext();const[documents,setDocuments]=useState<DocumentItem[]>([]);const[runs,setRuns]=useState<Array<Record<string,unknown>>>([]);const[selected,setSelected]=useState("");const[result,setResult]=useState<Result|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function load(){if(!context)return;const[docsResponse,runsResponse]=await Promise.all([fetch(`${context.apiUrl}/api/v2/documents?limit=250`,{headers:tenantHeaders(context)}),fetch(`${context.apiUrl}/api/v2/phase6c/parity`,{headers:tenantHeaders(context)})]);if(docsResponse.ok){const items=(await docsResponse.json()).items||[];setDocuments(items);setSelected(current=>current||items[0]?.id||"")}if(runsResponse.ok)setRuns((await runsResponse.json()).items||[])}
  useEffect(()=>{void load()},[]);
  async function execute(mode:"LEGACY_REFERENCE"|"V2_NATIVE"|"COMPARE"){if(!context||!selected)return;setBusy(true);setMessage("");const response=await fetch(`${context.apiUrl}/api/v2/phase6c/documents/${selected}/execute`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({mode})});const body=await response.json().catch(()=>({}));if(response.ok){setResult(body);const draft=body.v2?.draft_template;setMessage(draft?`New format detected. V2 draft ${draft.template_version} is ready in Template Studio for AI-assisted mapping, tests, and human approval.`:mode==="COMPARE"?"Both engines ran independently. No reference values were supplied to V2.":`${mode} execution recorded.`);await load()}else setMessage(typeof body.detail==="string"?body.detail:"Execution failed.");setBusy(false)}
  if(!context)return <div className="config-state">Sign in and select an authorized company.</div>;
  const fields=result?.comparison?.fields||[];return <div className="phase6c-stack">{message&&<p className="inline-message" role="status">{message}</p>}<section className="panel parity-control"><div><p className="eyebrow">Independent execution</p><h2>Choose a stored PDF</h2><select value={selected} onChange={event=>setSelected(event.target.value)}>{documents.map(item=><option value={item.id} key={item.id}>{item.original_filename||item.filename||item.id} · {item.status}</option>)}</select></div><div className="parity-actions"><button className="filter-button" disabled={!selected||busy} onClick={()=>void execute("LEGACY_REFERENCE")}>Reference only</button><button className="filter-button" disabled={!selected||busy} onClick={()=>void execute("V2_NATIVE")}>V2 native only</button><button className="primary" disabled={!selected||busy} onClick={()=>void execute("COMPARE")}>{busy?"Running…":"Run independent comparison"}</button></div></section>
    {result&&<section className="panel"><div className="panel-heading"><div><p className="eyebrow">Run {result.run_id}</p><h2>Accounting Parity</h2></div><span className={`status ${result.comparison?.status==="MATCH"?"status-verified":result.comparison?.status==="BLOCKED"?"status-blocked":"status-review"}`}>{result.comparison?.status||String(result.v2?.status||result.reference?.status)}</span></div>{result.v2&&<div className="engine-evidence"><p><span>V2 engine</span><strong>{String(result.v2.engine)}</strong></p><p><span>Reference calls from V2_NATIVE</span><strong>{String(result.v2.reference_calls??"not applicable")}</strong></p><p><span>V2 template</span><strong>{String(result.v2.template_version||result.v2.reason||"—")}</strong></p></div>}{result.comparison?.reason&&<p className="issue"><strong>{result.comparison.reason}</strong> — create, test, and approve a V2 visual template in Template Studio. The reference result will not repair V2 automatically.</p>}{fields.length>0&&<div className="table-wrap"><table><thead><tr><th>Field</th><th>Legacy reference</th><th>V2 independent</th><th>Status</th></tr></thead><tbody>{fields.map(item=><tr key={item.field} className={item.status==="MATCH"?"":"difference-row"}><td><strong>{item.field.replaceAll("_"," ")}</strong></td><td>{value(item.legacy)}</td><td>{value(item.v2)}</td><td><span className={`status ${item.status==="MATCH"?"status-verified":"status-blocked"}`}>{item.status}</span></td></tr>)}</tbody></table></div>}</section>}
    <section className="panel"><p className="eyebrow">Stored evidence</p><h2>Recent comparisons</h2>{runs.length===0?<p className="muted">No comparisons have been recorded for this company.</p>:<div className="table-wrap"><table><thead><tr><th>Document</th><th>Mode</th><th>Reference</th><th>V2 template</th><th>Status</th><th>Created</th></tr></thead><tbody>{runs.map(run=><tr key={String(run.id)}><td>{String(run.filename)}</td><td>{String(run.mode)}</td><td>{String(run.legacy_template||"—")}</td><td>{String(run.v2_template_version_id||"—")}</td><td><span className={`status ${run.status==="MATCH"?"status-verified":run.status==="BLOCKED"?"status-blocked":"status-review"}`}>{String(run.status)}</span></td><td>{new Date(String(run.created_at)).toLocaleString()}</td></tr>)}</tbody></table></div>}</section></div>;
}
