"use client";

import Link from "next/link";
import { PointerEvent as ReactPointerEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { apiContext, tenantHeaders } from "../lib/api";
import { AiDocumentAssistant } from "./AiDocumentAssistant";

type Box = { x0: number; y0: number; x1: number; y1: number };
type StudioObject = { id: string; type: "FIELD"|"TABLE"|"ANCHOR"|"IGNORE_REGION"; box?: Box; field?: string; field_kind?: string; table_type?: string; page?: number; page_policy?: string; transforms?: string[]; columns?: Array<{ boundary: number; field: string }>; row_classifiers?: Array<{ text: string; row_type: string }>; multiline_strategy?: string; anchor_text?: string; relationship?: string; match_policy?: string; tolerance?: number; repeating?: boolean };
type Definition = { schema_version: number; document_mode: string; page_rules: Array<Record<string, unknown>>; objects: StudioObject[]; derived_fields: Array<{ field: string; formula: string; inputs: string[]; rounding: number }>; validation_profile: string; metadata: Record<string, unknown> };
type Sample = { document_id: string; original_filename: string; page_count: number; document_status: string; normalized_result?: Evidence; validation_status?: string; possible_outlier?: boolean };
type Version = { id: string; family_id: string; family_name: string; document_type: string; version: number; status: string; revision: number; engine: string; parent_version_id?: string; definition: Definition; samples: Sample[] };
type Evidence = { fields?: Array<{ name: string; value: unknown; source?: { page_number?: number; bounding_box?: Record<string, number> } }>; pages?: Array<{ page_number: number; width: number; height: number; text_blocks?: unknown[]; tables?: unknown[] }> };
type Preview = { extraction: { fields: Array<{ field: string; value: string; source?: { page_number?: number }; rule_id?: string; why: string; derived: boolean }>; item_rows: unknown[]; tax_buckets: unknown[]; warnings: string[] }; validation: { status: string; findings: Array<{ code: string; message: string; field?: string }> } };
type TestRun = { id: string; status: string; total: number; processed: number; verified: number; review: number; blocked: number; failed: number; results: Array<{ document_id: string; original_filename: string; result: string; validation: { checks?: Record<string, boolean> }; comparison: { differences?: unknown[] } }> };
type Tool = "POINTER"|"PAN"|"TEXT"|"REGION"|"TABLE"|"ROW"|"COLUMN"|"FIELD"|"IGNORE"|"ANCHOR";

const TOOLS: Array<{ key: Tool; label: string; shortcut?: string }> = [
  {key:"POINTER",label:"Pointer",shortcut:"V"},{key:"PAN",label:"Pan",shortcut:"H"},{key:"TEXT",label:"Text select"},
  {key:"REGION",label:"Region",shortcut:"R"},{key:"TABLE",label:"Table",shortcut:"T"},{key:"ROW",label:"Row"},{key:"COLUMN",label:"Column"},
  {key:"FIELD",label:"Field"},{key:"IGNORE",label:"Ignore"},{key:"ANCHOR",label:"Anchor"},
];
const FIELD_OPTIONS = ["invoice_number","invoice_date","reference_number","document_type","currency","supplier_name","supplier_gstin","buyer_name","buyer_gstin","place_of_supply","item_name","sku","hsn_sac","quantity","unit","unit_price","taxable_amount","gst_rate","cgst","sgst","igst","tax_amount","line_total","total_quantity","subtotal","taxable_total","cgst_total","sgst_total","igst_total","tax_total","round_off","invoice_total","transaction_date","value_date","narration","reference","debit","credit","balance","opening_balance","closing_balance"];
const COLUMN_OPTIONS = ["item_name","hsn_sac","quantity","unit","unit_price","taxable_amount","gst_rate","tax_amount","cgst","sgst","igst","line_total","transaction_date","value_date","narration","reference","debit","credit","balance"];

function errorMessage(value: unknown) { return value instanceof Error ? value.message : "Template Studio operation failed"; }
function clamp(value: number) { return Math.max(0, Math.min(1, value)); }
function sameDefinition(a: Definition, b: Definition) { return JSON.stringify(a) === JSON.stringify(b); }

export function StudioLauncher() {
  const context = apiContext(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({name:"",document_type:"Tax Invoice",supplier:"",description:"",mode:"INVOICE"});
  useEffect(() => { if (!context) return; const documentId = new URLSearchParams(window.location.search).get("documentId"); if (!documentId) return;
    setBusy(true); fetch(`${context.apiUrl}/api/v2/template-studio/from-document`, {method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({document_id:documentId})})
      .then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.detail?.message || body.detail || "Draft creation failed"); window.location.href=`/template-studio/${body.version.id}`; })
      .catch(reason => {setMessage(errorMessage(reason));setBusy(false);}); }, [context]);
  async function create() { if (!context) return; setBusy(true); setMessage(""); try { const response = await fetch(`${context.apiUrl}/api/v2/templates/families`, {method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify(form)}); const body=await response.json(); if(!response.ok) throw new Error(body.detail?.message||body.detail||"Template creation failed"); window.location.href=`/template-studio/${body.version.id}`; } catch(reason){setMessage(errorMessage(reason));setBusy(false);} }
  return <main className="studio-launcher"><Link href="/templates" className="studio-back">← Template Library</Link><section><p className="eyebrow">Deterministic authoring</p><h1>{busy ? "Preparing protected document evidence…" : "Create a Template Studio workspace"}</h1><p>Build a safe visual rule template. No AI or external document service is active in Phase 4.</p>
    {message&&<div className="studio-error">{message}</div>}<div className="launch-grid"><label>Family name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Amazon Fee Invoice" /></label><label>Document type<input value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})} /></label><label>Mode<select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}>{["INVOICE","MARKETPLACE","BANK","STOCK_TRANSFER","GENERIC"].map(value=><option key={value}>{value}</option>)}</select></label><label>Supplier / platform<input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})} /></label><label className="wide">Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} /></label></div><button className="primary" disabled={busy||form.name.length<2} onClick={create}>Create draft workspace</button></section></main>;
}

function ProtectedPage({ documentId, page, zoom, children, onPointerDown, cursor }: {documentId:string;page:number;zoom:number;children:React.ReactNode;onPointerDown:(e:ReactPointerEvent<HTMLDivElement>)=>void;cursor:string}) {
  const context=apiContext(); const [url,setUrl]=useState("");
  useEffect(()=>{if(!context)return;let active=true,objectUrl="";fetch(`${context.apiUrl}/api/v2/documents/${documentId}/pages/${page}/image`,{headers:tenantHeaders(context)}).then(r=>{if(!r.ok)throw new Error();return r.blob()}).then(blob=>{objectUrl=URL.createObjectURL(blob);if(active)setUrl(objectUrl)}).catch(()=>active&&setUrl(""));return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[context,documentId,page]);
  return <div className="studio-page-scroll"><div className="studio-page" style={{width:`${zoom}%`,cursor}} onPointerDown={onPointerDown}>{url?<img draggable={false} src={url} alt={`Sample PDF page ${page}`} />:<div className="studio-page-empty">Protected page preview unavailable</div>}{children}</div></div>;
}

export function TemplateStudio({versionId}:{versionId:string}) {
  const context=apiContext(); const [version,setVersion]=useState<Version|null>(null); const [definition,setDefinition]=useState<Definition|null>(null); const [saved,setSaved]=useState<Definition|null>(null);
  const [activeSample,setActiveSample]=useState(0); const [page,setPage]=useState(1); const [zoom,setZoom]=useState(90); const [tool,setTool]=useState<Tool>("POINTER"); const [selectedId,setSelectedId]=useState<string|null>(null);
  const [draftBox,setDraftBox]=useState<Box|null>(null); const [gesture,setGesture]=useState<{kind:"create"|"move"|"resize";startX:number;startY:number;before:Definition;objectId?:string;original?:Box}|null>(null);
  const [undo,setUndo]=useState<Definition[]>([]); const [redo,setRedo]=useState<Definition[]>([]); const [saveState,setSaveState]=useState("Saved"); const [error,setError]=useState("");
  const [preview,setPreview]=useState<Preview|null>(null); const [testRun,setTestRun]=useState<TestRun|null>(null); const [bottomTab,setBottomTab]=useState("preview"); const [inspectorTab,setInspectorTab]=useState("fields"); const [palette,setPalette]=useState(false);
  const [sampleId,setSampleId]=useState(""); const [versionDiff,setVersionDiff]=useState<{added:StudioObject[];removed:StudioObject[];changed:Array<{id:string;before:StudioObject;after:StudioObject}>;old_version:number;new_version:number}|null>(null);
  const canvasRef=useRef<HTMLDivElement|null>(null);
  const load=useCallback(async()=>{if(!context)return;const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}`,{headers:tenantHeaders(context)});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Template failed to load");setVersion(body);setDefinition(body.definition);setSaved(body.definition);},[context,versionId]);
  useEffect(()=>{load().catch(reason=>setError(errorMessage(reason)))},[load]);
  const sample=version?.samples?.[activeSample]; const pageCount=sample?.page_count||1; const selected=definition?.objects.find(item=>item.id===selectedId)||null; const editable=version?.status==="DRAFT"||version?.status==="TESTING";
  const dirty=Boolean(definition&&saved&&!sameDefinition(definition,saved));
  const commit=useCallback((next:Definition,before?:Definition)=>{if(!definition||!editable)return;setUndo(stack=>[...stack,structuredClone(before||definition)].slice(-100));setRedo([]);setDefinition(next);setSaveState("Unsaved changes")},[definition,editable]);
  const saveDraft=useCallback(async(silent=false)=>{if(!context||!definition||!version||!editable)return version;setSaveState("Saving…");try{const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}`,{method:"PUT",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({revision:version.revision,definition})});const body=await response.json();if(response.status===409){setSaveState("Conflict");throw new Error("This template was changed by another user. Reload or clone before saving.")}if(!response.ok)throw new Error(body.detail?.message||body.detail||"Save failed");setVersion({...version,...body,definition});setSaved(structuredClone(definition));setSaveState("Saved");return {...version,...body,definition};}catch(reason){setSaveState("Save failed");if(!silent)setError(errorMessage(reason));throw reason}},[context,definition,editable,version,versionId]);
  useEffect(()=>{if(!dirty||!editable)return;const timer=window.setTimeout(()=>void saveDraft(true).catch(()=>undefined),1800);return()=>window.clearTimeout(timer)},[dirty,editable,saveDraft]);
  const doUndo=useCallback(()=>{if(!definition||!undo.length||!editable)return;const prior=undo[undo.length-1];setRedo(stack=>[...stack,structuredClone(definition)]);setUndo(stack=>stack.slice(0,-1));setDefinition(prior);setSaveState("Unsaved changes")},[definition,undo,editable]);
  const doRedo=useCallback(()=>{if(!definition||!redo.length||!editable)return;const next=redo[redo.length-1];setUndo(stack=>[...stack,structuredClone(definition)]);setRedo(stack=>stack.slice(0,-1));setDefinition(next);setSaveState("Unsaved changes")},[definition,redo,editable]);
  const removeSelected=useCallback(()=>{if(!definition||!selectedId||!editable)return;commit({...definition,objects:definition.objects.filter(item=>item.id!==selectedId)});setSelectedId(null)},[definition,selectedId,editable,commit]);
  useEffect(()=>{function keydown(event:KeyboardEvent){const typing=(event.target as HTMLElement)?.matches("input,select,textarea");if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setPalette(value=>!value);return}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="s"){event.preventDefault();void saveDraft();return}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?doRedo():doUndo();return}if(typing)return;if(event.key==="Delete")removeSelected();else if(event.key==="Escape"){setSelectedId(null);setPalette(false)}else if(event.key.toLowerCase()==="v")setTool("POINTER");else if(event.key.toLowerCase()==="h")setTool("PAN");else if(event.key.toLowerCase()==="r")setTool("REGION");else if(event.key.toLowerCase()==="t")setTool("TABLE");else if(event.key==="+"||event.key==="=")setZoom(value=>Math.min(220,value+10));else if(event.key==="-")setZoom(value=>Math.max(40,value-10))}window.addEventListener("keydown",keydown);return()=>window.removeEventListener("keydown",keydown)},[doRedo,doUndo,removeSelected,saveDraft]);
  function point(event:ReactPointerEvent){const rect=event.currentTarget.getBoundingClientRect();return{x:clamp((event.clientX-rect.left)/rect.width),y:clamp((event.clientY-rect.top)/rect.height)}}
  function canvasPoint(event:ReactPointerEvent){const element=(event.target as HTMLElement).closest?.(".studio-page") as HTMLElement|null;const rect=element?.getBoundingClientRect();if(!rect)return{x:0,y:0};return{x:clamp((event.clientX-rect.left)/rect.width),y:clamp((event.clientY-rect.top)/rect.height)}}
  function canvasDown(event:ReactPointerEvent<HTMLDivElement>){if(!definition||!editable||!["REGION","TABLE","FIELD","IGNORE"].includes(tool)||event.target!==event.currentTarget&&!(event.target as HTMLElement).tagName.match(/IMG/))return;const p=point(event);event.currentTarget.setPointerCapture(event.pointerId);setGesture({kind:"create",startX:p.x,startY:p.y,before:structuredClone(definition)});setDraftBox({x0:p.x,y0:p.y,x1:p.x+0.001,y1:p.y+0.001})}
  function canvasMove(event:ReactPointerEvent<HTMLDivElement>){if(!gesture||!definition)return;const p=canvasPoint(event);if(gesture.kind==="create")setDraftBox({x0:Math.min(gesture.startX,p.x),y0:Math.min(gesture.startY,p.y),x1:Math.max(gesture.startX,p.x),y1:Math.max(gesture.startY,p.y)});else if(gesture.objectId&&gesture.original){const dx=p.x-gesture.startX,dy=p.y-gesture.startY;const original=gesture.original;const box=gesture.kind==="move"?{x0:clamp(original.x0+dx),y0:clamp(original.y0+dy),x1:clamp(original.x1+dx),y1:clamp(original.y1+dy)}:{...original,x1:Math.max(original.x0+.01,clamp(original.x1+dx)),y1:Math.max(original.y0+.01,clamp(original.y1+dy))};setDefinition({...definition,objects:definition.objects.map(item=>item.id===gesture.objectId?{...item,box}:item)})}}
  function canvasUp(){if(!gesture||!definition)return;if(gesture.kind==="create"&&draftBox&&(draftBox.x1-draftBox.x0)>.01&&(draftBox.y1-draftBox.y0)>.01){const id=crypto.randomUUID();const base={id,box:draftBox,page_policy:"PAGE_NUMBER",page};let object:StudioObject=tool==="TABLE"?{...base,type:"TABLE",table_type:"ITEM",page_policy:"TABLE_REPEAT",columns:[{boundary:.2,field:"item_name"},{boundary:.4,field:"hsn_sac"},{boundary:.6,field:"quantity"},{boundary:.8,field:"gst_rate"}],row_classifiers:[{text:"Total",row_type:"TOTAL"}],multiline_strategy:"same-cell",repeating:true}:tool==="IGNORE"?{...base,type:"IGNORE_REGION"}:{...base,type:"FIELD",field:"unmapped_field",field_kind:"CUSTOM",transforms:["trim"]};commit({...definition,objects:[...definition.objects,object]},gesture.before);setSelectedId(id)}else if(gesture.kind!=="create"&&!sameDefinition(gesture.before,definition))commit(definition,gesture.before);setGesture(null);setDraftBox(null)}
  function objectDown(event:ReactPointerEvent,object:StudioObject,kind:"move"|"resize"="move"){event.stopPropagation();if(!editable||tool!=="POINTER"||!object.box)return;const rect=(event.currentTarget.closest(".studio-page") as HTMLElement).getBoundingClientRect();setSelectedId(object.id);setGesture({kind,startX:clamp((event.clientX-rect.left)/rect.width),startY:clamp((event.clientY-rect.top)/rect.height),before:structuredClone(definition!),objectId:object.id,original:{...object.box}});(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId)}
  function updateSelected(patch:Partial<StudioObject>){if(!definition||!selected)return;commit({...definition,objects:definition.objects.map(item=>item.id===selected.id?{...item,...patch}:item)})}
  async function runPreview(){if(!context||!version||!sample)return;try{if(dirty)await saveDraft();const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}/preview`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({evidence:sample.normalized_result||{}})});const body=await response.json();if(!response.ok)throw new Error(body.detail?.message||body.detail);setPreview(body);setBottomTab("preview")}catch(reason){setError(errorMessage(reason))}}
  async function testAll(){if(!context)return;try{if(dirty)await saveDraft();const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}/test-all`,{method:"POST",headers:tenantHeaders(context)});const body=await response.json();if(!response.ok)throw new Error(body.detail?.message||body.detail);setBottomTab("tests");pollRun(body.test_run_id)}catch(reason){setError(errorMessage(reason))}}
  function pollRun(id:string){if(!context)return;const tick=async()=>{const response=await fetch(`${context.apiUrl}/api/v2/template-test-runs/${id}`,{headers:tenantHeaders(context)});if(!response.ok)return;const body=await response.json();setTestRun(body);if(body.status==="QUEUED"||body.status==="RUNNING")window.setTimeout(tick,700)};void tick()}
  async function approve(){if(!context)return;try{const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}/approve`,{method:"POST",headers:tenantHeaders(context)});const body=await response.json();if(!response.ok)throw new Error(body.detail?.message||body.detail);setVersion({...version!,...body});setSaveState("Approved · immutable")}catch(reason){setError(errorMessage(reason))}}
  async function clone(){if(!context)return;try{const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}/clone`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({change_summary:`Draft cloned from v${version?.version}`})});const body=await response.json();if(!response.ok)throw new Error(body.detail?.message||body.detail);window.location.href=`/template-studio/${body.id}`}catch(reason){setError(errorMessage(reason))}}
  async function attachSample(){if(!context||!sampleId)return;try{const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}/samples`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({document_id:sampleId,notes:"Attached from Template Studio"})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail?.message||body.detail||"Sample attachment failed");setSampleId("");await load()}catch(reason){setError(errorMessage(reason))}}
  async function removeSample(documentId:string){if(!context)return;try{const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}/samples/${documentId}`,{method:"DELETE",headers:tenantHeaders(context)});if(!response.ok)throw new Error("Sample removal failed");setActiveSample(0);await load()}catch(reason){setError(errorMessage(reason))}}
  async function saveGolden(){if(!context||!sample||!preview)return;try{const fields=Object.fromEntries(preview.extraction.fields.map(item=>[item.field,item.value]));const response=await fetch(`${context.apiUrl}/api/v2/templates/versions/${versionId}/samples`,{method:"POST",headers:{...tenantHeaders(context),"Content-Type":"application/json"},body:JSON.stringify({document_id:sample.document_id,expected_result:{fields,item_rows:preview.extraction.item_rows,tax_buckets:preview.extraction.tax_buckets},notes:"Golden output verified in Template Studio"})});if(!response.ok)throw new Error("Golden output save failed");setSaveState("Golden output saved");await load()}catch(reason){setError(errorMessage(reason))}}
  async function compareParent(){const current=version;if(!context||!current?.parent_version_id)return;try{const response=await fetch(`${context.apiUrl}/api/v2/templates/diff?old=${current.parent_version_id}&new=${versionId}`,{headers:tenantHeaders(context)});if(!response.ok)throw new Error("Version comparison failed");setVersionDiff(await response.json());setBottomTab("diff")}catch(reason){setError(errorMessage(reason))}}
  if(error&&!version)return <main className="studio-fatal"><h1>Template Studio could not open</h1><p>{error}</p><Link href="/templates">Return to templates</Link></main>;
  if(!version||!definition)return <main className="studio-fatal"><h1>Opening Template Studio…</h1><p>Loading version, samples and protected evidence.</p></main>;
  const pageObjects=definition.objects.filter(item=>!item.page||item.page===page||item.page_policy==="PAGE_ANY"||item.page_policy==="TABLE_REPEAT");
  return <div className="template-studio" ref={canvasRef} onPointerMove={canvasMove} onPointerUp={canvasUp}>
    <header className="studio-toolbar"><Link href={`/templates/${version.family_id}`} className="icon-button" title="Back to family">←</Link><div className="studio-title"><strong>{version.family_name}</strong><span>v{version.version} · {version.status} · {definition.document_mode.replaceAll("_"," ")}</span></div>
      <div className="studio-sample-select"><span>Sample</span><select value={activeSample} onChange={e=>{setActiveSample(Number(e.target.value));setPage(1)}}>{version.samples.length?version.samples.map((item,index)=><option value={index} key={item.document_id}>{item.original_filename}</option>):<option>No samples attached</option>}</select></div>
      <button onClick={runPreview} disabled={!sample}>Test current</button><button onClick={testAll} disabled={!version.samples.length}>Test all</button><button onClick={()=>setInspectorTab("validation")}>Validate</button>
      {version.parent_version_id&&<button onClick={compareParent}>Compare v{version.version-1} → v{version.version}</button>}{editable?<><button onClick={()=>void saveDraft()}>{saveState}</button><button className="approve-button" onClick={approve}>Approve</button></>:<button onClick={clone}>Clone to v{version.version+1} draft</button>}
    </header>
    <div className="studio-tools" role="toolbar" aria-label="Canvas tools">{TOOLS.map(item=><button key={item.key} className={tool===item.key?"active":""} onClick={()=>setTool(item.key)} title={`${item.label}${item.shortcut?` (${item.shortcut})`:""}`}>{item.label}<small>{item.shortcut}</small></button>)}<span className="tool-separator"/><button disabled={!undo.length} onClick={doUndo}>Undo</button><button disabled={!redo.length} onClick={doRedo}>Redo</button><span className="tool-separator"/><button onClick={()=>setZoom(Math.max(40,zoom-10))}>−</button><span>{zoom}%</span><button onClick={()=>setZoom(Math.min(220,zoom+10))}>+</button><button onClick={()=>setZoom(100)}>Fit width</button><button onClick={()=>setZoom(72)}>Fit page</button><button onClick={()=>setPalette(true)}>Commands <small>Ctrl K</small></button></div>
    {error&&<div className="studio-error-bar"><span>{error}</span><button onClick={()=>setError("")}>Dismiss</button></div>}
    <div className="studio-body">
      <aside className="studio-left"><div className="panel-tabs"><button className="active">Pages</button><button>Samples</button><button>Layers</button><button>Versions</button></div><div className="page-thumbnails">{Array.from({length:pageCount},(_,index)=>{const number=index+1;const count=definition.objects.filter(item=>item.page===number).length;return <button key={number} className={page===number?"active":""} onClick={()=>setPage(number)}><span className="thumbnail-sheet">{number}</span><div><strong>Page {number}</strong><small>{count} mappings · {sample?.normalized_result?.pages?.[index]?.tables ? "tables detected" : "native evidence"}</small></div></button>})}</div>
        <div className="sample-stack"><p className="eyebrow">Samples ({version.samples.length})</p>{version.samples.map((item,index)=><div className={`sample-line ${activeSample===index?"active":""}`} key={item.document_id}><button onClick={()=>{setActiveSample(index);setPage(1)}}><span>{item.validation_status==="VERIFIED"?"✓":item.validation_status?"⚠":"○"}</span><div><strong>{item.original_filename}</strong><small>{item.page_count} pages · {item.document_status}{item.possible_outlier?" · Possible outlier":""}</small></div></button>{editable&&<button title="Remove draft sample" onClick={()=>removeSample(item.document_id)}>×</button>}</div>)}{!version.samples.length&&<p>No protected samples attached. Add a tenant-scoped document ID below.</p>}{editable&&<div className="sample-add"><input value={sampleId} onChange={e=>setSampleId(e.target.value)} placeholder="Protected document UUID"/><button onClick={attachSample} disabled={!sampleId}>Add</button></div>}</div></aside>
      <section className="studio-canvas"><ProtectedPage documentId={sample?.document_id||"missing"} page={page} zoom={zoom} cursor={tool==="PAN"?"grab":tool==="POINTER"?"default":"crosshair"} onPointerDown={canvasDown}>
        {pageObjects.map(object=>object.box&&<div key={object.id} onPointerDown={event=>objectDown(event,object)} className={`mapping-overlay mapping-${object.type.toLowerCase()} ${selectedId===object.id?"selected":""}`} style={{left:`${object.box.x0*100}%`,top:`${object.box.y0*100}%`,width:`${(object.box.x1-object.box.x0)*100}%`,height:`${(object.box.y1-object.box.y0)*100}%`}}><span>{object.type==="FIELD"?object.field:object.type==="TABLE"?`${object.table_type} · repeating`:"Ignored"}</span>{selectedId===object.id&&editable&&<button aria-label="Resize selection" className="resize-handle" onPointerDown={event=>objectDown(event,object,"resize")} />}{object.type==="TABLE"&&object.columns?.map((column,index)=><i key={index} style={{left:`${column.boundary*100}%`}} title={column.field}/>)}</div>)}
        {draftBox&&<div className="mapping-overlay mapping-draft" style={{left:`${draftBox.x0*100}%`,top:`${draftBox.y0*100}%`,width:`${(draftBox.x1-draftBox.x0)*100}%`,height:`${(draftBox.y1-draftBox.y0)*100}%`}} />}
      </ProtectedPage><div className="canvas-page-nav"><button onClick={()=>setPage(Math.max(1,page-1))} disabled={page===1}>Previous</button><span>Page {page} of {pageCount}</span><button onClick={()=>setPage(Math.min(pageCount,page+1))} disabled={page===pageCount}>Next</button></div></section>
      <aside className="studio-inspector"><div className="panel-tabs">{["fields","tables","rules","validation","properties"].map(tab=><button className={inspectorTab===tab?"active":""} onClick={()=>setInspectorTab(tab)} key={tab}>{tab}</button>)}</div>
        {selected?<div className="inspector-content"><p className="eyebrow">Selected {selected.type.replaceAll("_"," ")}</p><h2>{selected.field||selected.table_type||selected.type}</h2>{selected.type==="FIELD"&&<><label>Semantic field<select value={selected.field} onChange={e=>updateSelected({field:e.target.value})}>{FIELD_OPTIONS.map(value=><option key={value}>{value}</option>)}<option value="unmapped_field">Unmapped custom field</option></select></label><label>Page policy<select value={selected.page_policy} onChange={e=>updateSelected({page_policy:e.target.value})}>{["PAGE_ANY","PAGE_FIRST","PAGE_LAST","PAGE_NUMBER"].map(value=><option key={value}>{value}</option>)}</select></label><label>Transforms<select multiple value={selected.transforms} onChange={e=>updateSelected({transforms:Array.from(e.target.selectedOptions,item=>item.value)})}>{["trim","normalize_whitespace","remove_currency_symbol","remove_grouping_comma","parse_decimal","parse_date","normalize_percentage"].map(value=><option key={value}>{value}</option>)}</select></label></>}
          {selected.type==="ANCHOR"&&<><label>Target field<select value={selected.field} onChange={e=>updateSelected({field:e.target.value})}>{FIELD_OPTIONS.map(value=><option key={value}>{value}</option>)}</select></label><label>Label / anchor text<input value={selected.anchor_text||""} onChange={e=>updateSelected({anchor_text:e.target.value})}/></label><label>Relationship<select value={selected.relationship} onChange={e=>updateSelected({relationship:e.target.value})}>{["RIGHT_OF","LEFT_OF","BELOW","ABOVE","NEAREST","SAME_LINE"].map(value=><option key={value}>{value}</option>)}</select></label><label>Match policy<select value={selected.match_policy} onChange={e=>updateSelected({match_policy:e.target.value})}>{["EXACT","CASE_INSENSITIVE","NORMALIZED_PUNCTUATION"].map(value=><option key={value}>{value}</option>)}</select></label><label>Tolerance (max 0.20)<input type="number" min="0" max="0.2" step="0.01" value={selected.tolerance||0} onChange={e=>updateSelected({tolerance:Number(e.target.value)})}/></label></>}
          {selected.type==="TABLE"&&<><label>Table type<select value={selected.table_type} onChange={e=>updateSelected({table_type:e.target.value})}>{["ITEM","TAX_SUMMARY","PAYMENT","BANK","SUMMARY","GENERIC"].map(value=><option key={value}>{value}</option>)}</select></label><label>Multi-line cells<select value={selected.multiline_strategy} onChange={e=>updateSelected({multiline_strategy:e.target.value})}>{["same-cell","indent","no-numeric-neighbor","manual"].map(value=><option key={value}>{value}</option>)}</select></label><p className="eyebrow inspector-section">Column mapping</p>{selected.columns?.map((column,index)=><div className="column-editor" key={index}><input type="range" min="1" max="99" value={column.boundary*100} onChange={e=>updateSelected({columns:selected.columns!.map((item,i)=>i===index?{...item,boundary:Number(e.target.value)/100}:item)})}/><select value={column.field} onChange={e=>updateSelected({columns:selected.columns!.map((item,i)=>i===index?{...item,field:e.target.value}:item)})}>{COLUMN_OPTIONS.map(value=><option key={value}>{value}</option>)}</select><button onClick={()=>updateSelected({columns:selected.columns!.filter((_,i)=>i!==index)})}>×</button></div>)}<button onClick={()=>{const columns=selected.columns||[];updateSelected({columns:[...columns,{boundary:Math.min(.99,(columns.at(-1)?.boundary||0)+.1),field:"item_name"}]})}}>Add / split column</button><p className="eyebrow inspector-section">Row classifiers</p>{selected.row_classifiers?.map((rule,index)=><div className="column-editor" key={index}><input value={rule.text} onChange={e=>updateSelected({row_classifiers:selected.row_classifiers!.map((item,i)=>i===index?{...item,text:e.target.value}:item)})}/><select value={rule.row_type} onChange={e=>updateSelected({row_classifiers:selected.row_classifiers!.map((item,i)=>i===index?{...item,row_type:e.target.value}:item)})}>{["HEADER","ITEM","SUBTOTAL","TOTAL","TAX_SUMMARY","NOTE","IGNORE"].map(value=><option key={value}>{value}</option>)}</select><button onClick={()=>updateSelected({row_classifiers:selected.row_classifiers!.filter((_,i)=>i!==index)})}>×</button></div>)}<button onClick={()=>updateSelected({row_classifiers:[...(selected.row_classifiers||[]),{text:"Subtotal",row_type:"SUBTOTAL"}]})}>Add row classifier</button><p className="mapping-note">Repeating rows are mapped once. Header, totals, tax summaries, notes and ignored rows remain distinct.</p></>}
          <dl className="coordinate-grid"><div><dt>Page</dt><dd>{selected.page||"Any"}</dd></div>{selected.box&&Object.entries(selected.box).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value.toFixed(4)}</dd></div>)}</dl>{editable&&<button className="danger-button" onClick={removeSelected}>Delete mapping</button>}</div>:
          <div className="inspector-content"><p className="eyebrow">{inspectorTab}</p>{inspectorTab==="validation"?<><h2>Accounting validation</h2><span className={`status status-${(preview?.validation.status||"review").toLowerCase()}`}>{preview?.validation.status||"NOT RUN"}</span>{preview?.validation.findings.map(item=><div className="validation-finding" key={`${item.code}-${item.field}`}><strong>{item.code}</strong><p>{item.message}</p></div>)}<p className="mapping-note">Approval is blocked until all protected samples and golden outputs verify.</p></>:inspectorTab==="rules"?<><h2>Derived fields</h2>{definition.derived_fields.map((item,index)=><div className="derived-rule" key={index}><input value={item.field} onChange={e=>commit({...definition,derived_fields:definition.derived_fields.map((rule,i)=>i===index?{...rule,field:e.target.value}:rule)})}/><input value={item.formula} onChange={e=>commit({...definition,derived_fields:definition.derived_fields.map((rule,i)=>i===index?{...rule,formula:e.target.value}:rule)})}/><small>Inputs: {item.inputs.join(", ")} · rounding {item.rounding} · no arbitrary code</small></div>)}<button disabled={!editable} onClick={()=>commit({...definition,derived_fields:[...definition.derived_fields,{field:"tax_total",formula:"cgst_total + sgst_total + igst_total",inputs:["cgst_total","sgst_total","igst_total"],rounding:2}]})}>Add safe derived field</button></>:<><h2>Select a canvas object</h2><p>Use Field, Table or Ignore tools to draw a region. Switch to Pointer to move or resize it.</p><button disabled={!editable} onClick={()=>{if(!definition)return;const id=crypto.randomUUID();commit({...definition,objects:[...definition.objects,{id,type:"ANCHOR",field:"invoice_number",anchor_text:"Invoice No.",relationship:"RIGHT_OF",match_policy:"CASE_INSENSITIVE",tolerance:.05,page_policy:"PAGE_ANY"}]});setSelectedId(id)}}>Create label → value anchor</button></>}</div>}
      </aside>
    </div>
    <section className="studio-bottom"><div className="bottom-tabs">{[["preview","Extraction Preview"],["tests","Test Results"],["diff","Version Diff"],["why","Why / Source Trace"],["activity","Activity"],["assistant","Document Assistant"]].map(([id,label])=><button className={bottomTab===id?"active":""} key={id} onClick={()=>setBottomTab(id)}>{label}</button>)}</div>
      <div className="bottom-content">{bottomTab==="preview"&&<>{preview?<div className="preview-columns"><div><p className="eyebrow">Extracted fields</p>{preview.extraction.fields.map(item=><button key={`${item.field}-${item.rule_id}`} onClick={()=>{setSelectedId(item.rule_id||null);if(item.source?.page_number)setPage(item.source.page_number)}}><strong>{item.field}</strong><span>{item.value}</span><small>{item.source?.page_number?`Page ${item.source.page_number} · click for source`:item.derived?"Derived · explicit formula":"Source unavailable"}</small></button>)}</div><div><p className="eyebrow">Accounting structures</p><dl><div><dt>Item rows</dt><dd>{preview.extraction.item_rows.length}</dd></div><div><dt>Tax buckets</dt><dd>{preview.extraction.tax_buckets.length}</dd></div><div><dt>Warnings</dt><dd>{preview.extraction.warnings.length}</dd></div></dl>{editable&&<button onClick={saveGolden}>Verify &amp; save as golden output</button>}<small className="golden-note">Human verification is required before this sample can support approval.</small></div></div>:<div className="bottom-empty">Run “Test current” to see deterministic extraction, item rows, tax buckets and source trace.</div>}</>}
      {bottomTab==="tests"&&<>{testRun?<><div className="test-summary"><strong>{testRun.status}</strong><progress value={testRun.processed} max={testRun.total||1}/><span>{testRun.processed}/{testRun.total}</span><span className="verified">{testRun.verified} verified</span><span>{testRun.review} review</span><span>{testRun.blocked} blocked</span><span>{testRun.failed} failed</span></div><table><thead><tr><th>Document</th><th>Extraction</th><th>Golden</th><th>Validation</th><th>Result</th></tr></thead><tbody>{testRun.results.map(row=><tr key={row.document_id} onClick={()=>{const index=version.samples.findIndex(item=>item.document_id===row.document_id);if(index>=0)setActiveSample(index)}}><td>{row.original_filename}</td><td>PASS</td><td>{row.comparison?.differences?.length?`${row.comparison.differences.length} differences`:"MATCH"}</td><td>{row.validation?.checks?.required_fields===false?"Required fields failed":"PASS"}</td><td><span className={`status status-${row.result.toLowerCase()}`}>{row.result}</span></td></tr>)}</tbody></table></>:<div className="bottom-empty">Test all protected samples to populate the verification matrix.</div>}</>}
      {bottomTab==="diff"&&<>{versionDiff?<div className="version-diff"><strong>v{versionDiff.old_version} → v{versionDiff.new_version}</strong><span>{versionDiff.added.length} added</span><span>{versionDiff.changed.length} changed</span><span>{versionDiff.removed.length} removed</span>{versionDiff.changed.map(item=><div key={item.id}><code>{item.id}</code><small>Old: {item.before.type} {item.before.field||item.before.table_type} · New: {item.after.type} {item.after.field||item.after.table_type}</small></div>)}</div>:<div className="bottom-empty">{version.parent_version_id?"Use Compare in the top toolbar to inspect old and new mappings.":"This version has no parent version."}</div>}</>}
      {bottomTab==="why"&&<div className="why-panel">{selected?<><strong>{selected.field||selected.table_type||selected.type}</strong><p>Rule: {selected.type} mapping · {selected.page_policy||"PAGE_ANY"}</p><p>Source: Page {selected.page||"any"}{selected.box?` · [${selected.box.x0.toFixed(3)}, ${selected.box.y0.toFixed(3)}, ${selected.box.x1.toFixed(3)}, ${selected.box.y1.toFixed(3)}]`:" · anchor relationship"}</p><p>Evidence: deterministic geometry/label rule. No AI explanation generated.</p></>:<p>Select an extracted value or canvas mapping to inspect why it was chosen.</p>}</div>}
      {bottomTab==="activity"&&<div className="bottom-empty">Meaningful saves, tests, approvals, rule changes and comments are recorded in tenant-scoped PostgreSQL activity history.</div>}
      {bottomTab==="assistant"&&<AiDocumentAssistant versionId={versionId} revision={version.revision} selected={selected as unknown as Record<string,unknown>|null} onApplied={load}/>}</div>
    </section>
    {palette&&<div className="command-backdrop" onMouseDown={()=>setPalette(false)}><div className="command-palette" onMouseDown={e=>e.stopPropagation()}><input autoFocus placeholder="Type a deterministic command…"/><p className="eyebrow">Commands</p>{[["Add field",()=>setTool("FIELD")],["Add table",()=>setTool("TABLE")],["Test all samples",testAll],["Show failed validation",()=>setInspectorTab("validation")],["Fit page",()=>setZoom(72)],["Save draft",()=>void saveDraft()]].map(([label,handler])=><button key={String(label)} onClick={()=>{(handler as()=>void)();setPalette(false)}}>{String(label)}</button>)}<small>No general AI search. Ctrl+K opens this palette.</small></div></div>}
  </div>;
}
